### ISSUE TITLE
Issues about polarizable Martini model

### ISSUE THREAD

**Issue by Dropletsimuli** [maccallumlab/martini_openmm#3]
Hello,
I want to use  Martini 2.0 with polarizable water model ( doi:10.1371/journal.pcbi.1000810 )  on OpenMM-7.6.0. So, I modfied the relative permittivity to 2.5 in the martini_openmm.py. However, when I tested the system consisting of 10 water beads on OpenMM, there was  an error:
```
Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
Building system...
Performing energy minimization...
Simulating...
Traceback (most recent call last):
  File "pw_mix.py", line 72, in <module>
    simulation.step(steps)
  File "/home/zzx/research/tools/miniconda3/envs/openmm/lib/python3.7/site-packages/openmm/app/simulation.py", line 134, in step
    self._simulate(endStep=self.currentStep+steps)
  File "/home/zzx/research/tools/miniconda3/envs/openmm/lib/python3.7/site-packages/openmm/app/simulation.py", line 236, in _simulate
    self._generate_reports(wrapped, True)
  File "/home/zzx/research/tools/miniconda3/envs/openmm/lib/python3.7/site-packages/openmm/app/simulation.py", line 258, in _generate_reports
    reporter.report(self, state)
  File "/home/zzx/research/tools/miniconda3/envs/openmm/lib/python3.7/site-packages/openmm/app/dcdreporter.py", line 107, in report
    self._dcd.writeModel(state.getPositions(), periodicBoxVectors=state.getPeriodicBoxVectors())
  File "/home/zzx/research/tools/miniconda3/envs/openmm/lib/python3.7/site-packages/openmm/app/dcdfile.py", line 125, in writeModel
    raise ValueError('Particle position is NaN')
ValueError: Particle position is NaN
```
And then I found that if I remove the consitraints it would report another error:
```
Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
Building system...
Performing energy minimization...
Simulating...
Traceback (most recent call last):
  File "pw_mix.py", line 77, in <module>
    PDBFile.writeFile(simulation.topology, positions_3, open(pdb_name, 'w'))
  File "/home/zzx/research/tools/miniconda3/envs/openmm/lib/python3.7/site-packages/openmm/app/pdbfile.py", line 283, in writeFile
    PDBFile.writeModel(topology, positions, file, keepIds=keepIds, extraParticleIdentifier=extraParticleIdentifier)
  File "/home/zzx/research/tools/miniconda3/envs/openmm/lib/python3.7/site-packages/openmm/app/pdbfile.py", line 380, in writeModel
    recordName, atomIndex%100000, atomName, resName, chainName, resId, resIC, _format_83(coords[0]),
  File "/home/zzx/research/tools/miniconda3/envs/openmm/lib/python3.7/site-packages/openmm/app/pdbfile.py", line 464, in _format_83
    'in a width-8 field' % f)
ValueError: coordinate "-15682238.75" could not be represented in a width-8 field
```
It seems the system blows up. This is the .top file,
```
	;;;;;; CETYL TRIMETHYL AMMONIUM
	;;;;;; MARTINI FORCE FIELD ATOM TYPES

	#include "martini_v2.3P.itp"


    ;;;;;; POLARIZABLE WATER

    [ moleculetype ]
    ; molname       nrexcl
    PW              1

    [ atoms ]
    ;id type resnr residu atom cgnr   charge
     1   POL   1    PW     W    1      0
     2   D     1    PW     WP   2      0.46
     3   D     1    PW     WM   3     -0.46

    [constraints]
    ;  i     j   funct   length
       1     2    1       0.14
       1     3    1       0.14

    ; for minimization purposes constraints might be replaced by stiff bonds:
    ;
    ;[bonds]
    ;  i     j   funct   length   force const.
    ;   1     2    1       0.14    50000
    ;   1     3    1       0.14    50000

    [angles]
    ;   i    j   k   funct  angle    fc
        2    1   3    2     0.0     4.2

    [exclusions]
    1 2 3
    2 3


	[ system ]
	pw_mix

	[ molecules ]
	;molecule name   nr.
        PW 10

```
and this is .gro file,
```
Built with Packmol
   30
    1PW      PO    1   2.589   1.462   4.544
    1PW      PH    2   2.583   1.322   4.546
    1PW      PH    3   2.594   1.602   4.541
    2PW      PO    4   1.941   3.156   1.618
    2PW      PH    5   1.873   3.098   1.726
    2PW      PH    6   2.008   3.213   1.510
    3PW      PO    7   0.133   3.571   1.780
    3PW      PH    8   0.074   3.466   1.851
    3PW      PH    9   0.193   3.676   1.709
    4PW      PO   10   0.670   4.743   2.423
    4PW      PH   11   0.740   4.801   2.529
    4PW      PH   12   0.600   4.684   2.317
    5PW      PO   13   1.694   1.825   2.098
    5PW      PH   14   1.753   1.891   2.206
    5PW      PH   15   1.635   1.760   1.989
    6PW      PO   16   4.735   4.377   2.023
    6PW      PH   17   4.722   4.510   2.065
    6PW      PH   18   4.747   4.244   1.982
    7PW      PO   19   0.707   3.721   2.566
    7PW      PH   20   0.830   3.787   2.549
    7PW      PH   21   0.584   3.656   2.583
    8PW      PO   22   4.213   4.814   4.476
    8PW      PH   23   4.183   4.948   4.504
    8PW      PH   24   4.242   4.681   4.447
    9PW      PO   25   4.870   3.282   3.078
    9PW      PH   26   4.815   3.410   3.064
    9PW      PH   27   4.925   3.154   3.092
   10PW      PO   28   2.187   1.839   3.503
   10PW      PH   29   2.248   1.718   3.542
   10PW      PH   30   2.127   1.959   3.465
   5.00000   5.00000   5.00000
```
and this is .py file,
```
from openmm.app import *
from openmm import *
from openmm.unit import *
import martini

# Input Files

input_name = 'pw_mix2'
gro_name = input_name + '.gro'
top_name = input_name + '.top'

gpu_index = "0"
gro = GromacsGroFile(gro_name)
top = martini.GromacsMartiniV2TopFile(top_name, periodicBoxVectors=gro.getPeriodicBoxVectors())

#  production output setting

dcd_period = 100
log_period = 100
chk_period = 1000
steps = 20000  # 1 μs

output_file_name = 'output_p/'
output_name = input_name
dcd_name = output_file_name + output_name + '.dcd'
log_name = output_file_name + output_name + '.log'
chk_name = output_file_name + output_name + '.chk'
xml_name = output_file_name + output_name + '.xml'
pdb_name = output_file_name + output_name + '.pdb'

# Integration Options

nonbondedCutoff = 1.1 * nanometers
dt = 0.025 * picoseconds  # timestep
temperature = 300 * kelvin
friction = 1.0 / picosecond
pressure = 1.0 * atmospheres
barostatInterval = 25

# Simulation Options and Prepare the Simulation

print('Building system...')

platform = Platform.getPlatformByName('CUDA')
platformProperties = {'Precision': 'single', 'DeviceIndex': gpu_index}

topology = top.topology
positions = gro.positions
system = top.createSystem(nonbondedCutoff=nonbondedCutoff, epsilon_r=2.5)
system.addForce(MonteCarloBarostat(pressure, temperature, barostatInterval))
integrator = LangevinMiddleIntegrator(temperature, friction, dt)
simulation = Simulation(topology, system, integrator, platform, platformProperties)
simulation.context.setPositions(positions)

# Minimize and Equilibrate

print('Performing energy minimization...')
simulation.minimizeEnergy()

print('Simulating...')

dcdReporter = DCDReporter(dcd_name, dcd_period)
dataReporter = StateDataReporter(log_name, log_period, totalSteps=steps, \
                                 step=True, speed=True, progress=True, potentialEnergy=True, temperature=True, \
                                 volume=True, remainingTime=True, separator='\t')
checkpointReporter = CheckpointReporter(chk_name, chk_period)
simulation.reporters.append(dcdReporter)
simulation.reporters.append(dataReporter)
simulation.reporters.append(checkpointReporter)

simulation.currentStep = 0
simulation.step(steps)

simulation.saveState(xml_name)  # save done_state data
positions_3 = simulation.context.getState(getVelocities=True, getPositions=True, getForces=True, getEnergy=True,
                                          getParameters=True, groups=-1).getPositions()
PDBFile.writeFile(simulation.topology, positions_3, open(pdb_name, 'w'))
```
How can I fix this error or implement the polarizable water model on the martini_openmm.py? 

Best,
Drep

**Comment by Dropletsimuli** [comment]
When the precision is 'double' on GPU platform, it can run normally. But I can not find the reason out.

**Comment by jlmaccal** [comment]
We haven't really explored the polarizable model yet. I'll add your system as a test and see what I can find.

**Comment by jlmaccal** [comment]
Do you have a corresponding mdp file?

**Comment by jlmaccal** [comment]
Can you check using the latest `martini3` branch? That reproduces the forces and energies exactly for a polarizable water box.

If there are still issues, they likely come down to the friction coefficient of the integrator or the constraint algorithm. For what it's worth, we have yet to actually try to run a simulation with this implementation—we've been focusing on implementing all of the potential terms and validating that the energy / forces match.

**Comment by jlmaccal** [comment]
Just a note, that you can now specify `epsilon_r` when you load the topology. Set this to 2.5 for polarizable martini.

**Comment by Dropletsimuli** [comment]
> Do you have a corresponding mdp file?
The mdp file I used as follow:
```
	; Run control parameters
	integrator                = md         ; molecular dynamics integrator
	nsteps                    = 50000      ; number of steps
	dt                        = 0.020      ; time step for integration; total time: 100ns

	; Output control options
	nstlog                    = 5000      ; write energies to the log file
	nstcalcenergy             = 0          ; calculate energies every this many steps
	nstenergy                 = 5000      ; write energies to energy file
	;nstvout			      = 5000
	;nstxout                  = 5000      ; write positions and velocities to trr file
	nstxtcout                 = 500

	;Neighbour searching parameters
	cutoff-scheme             = Verlet     ; particle based cutoff
	verlet-buffer-tolerance   = -1
	rlist                     = 2.0        ; cutoff distance for long range neighbor list

        ; With the polarizable water model, the relative electrostatic screening
        ; (epsilon_r) should have a value of 2.5, representative of a low-dielectric
        ; apolar solvent. The polarizable water itself will perform the explicit screening
        ; in aqueous environment.

        coulombtype              = Shift; PME can also be used with the polariable model
        rcoulomb_switch          = 0.0
        rcoulomb                 = 1.2
        epsilon_r                = 2.5
        vdw_type                 = Shift
        rvdw_switch              = 0.9
        rvdw                     = 1.2
        DispCorr                 = No
		                               
	; Generate velocities                  
	gen-vel                   = yes        ; generate velocities
	gen-temp                  = 300     ; temperature for Maxwell distribution
		                               
	; Options for thermostat  
	tcoupl                    = v-rescale 
	tc-grps                   = system     ; groups to couple to temperature bath
	tau-t                     = 1.0        ; time constant
	ref-t                     = 300     ; reference temperature

	; Options for barostat
	pcoupl                    = parrinello-rahman  ; pressure coupling method
	pcoupltype                = isotropic          ; type of pressure coupling
	tau-p                     = 12.0               ; time constant (ps)
	ref-p                     = 1.01325            ; reference  pressure (bar)
	compressibility           = 3e-4               ; compressibility (1/bar)

        constraints              = none
        constraint_algorithm     = Lincs
        unconstrained_start      = no
        lincs_order              = 4
        lincs_warnangle          = 30
```

**Comment by Dropletsimuli** [comment]
> Can you check using the latest `martini3` branch? That reproduces the forces and energies exactly for a polarizable water box.
> 
> If there are still issues, they likely come down to the friction coefficient of the integrator or the constraint algorithm. For what it's worth, we have yet to actually try to run a simulation with this implementation—we've been focusing on implementing all of the potential terms and validating that the energy / forces match.

Thanks for your replay indeed. I will check it with MARTINI-3.0. There are few works about how to map the AA model to CG model for our system with MARTINI-3.0 currently. It was still a problem for me and I need to more time to learn about the mapping rule of MARTINI-3.0.

**Comment by Dropletsimuli** [comment]
@jlmaccal There was a error:
```
# Add explicitly specified constraints.
                for fields in molecule_type.constraints:
                    atoms = [int(x) - 1 for x in fields[:2]]
                    length = float(fields[2])
                    sys.addConstraint(
                        base_atom_index + atoms[0], base_atom_index + atoms[1], length
                    )
```
` length = float(fields[2])`should correct to `length = float(fields[3])`.

**Comment by jlmaccal** [comment]
Sorry, I meant try with the `martini3` branch of this repository. It has the latest changes and works for both martini2 and martini3.

**Comment by Dropletsimuli** [comment]
Ok, I will try with the branch.
